Feat/complete itemstock data transfer
eclipse-tractusx/puris pull request #170
Opened 2024-01-15 09:14 UTC by eschrewe

- added controllers for item stock api assets (request, response, statusrequest)
- added these endpoint to security config, replacing previous api endpoints
- added method in EdcAdapterService to support contracting for these assets
- added procedure to register status request api asset
- included status request in DT_ApiMethod enum
- added additional properties to DT_ApiMethod enum in order to register and identify them in catalog requests
- added Entity to persist sent or received messages
- added repo and service for this Entity
- completed workflows for handling requests and responses in ItemStockRequestApiServices
- updated sample data in DataInjectionCommandLineRunner

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-01-17 07:02 UTC, tom-rm-meyer-ISST requested changes
Overall great PR. 
Some license headers are missing. Beside that we should check if we update the helm chart in a separate Issue.  Let's discuss directly how to tacke log injections directly.

2024-01-17 15:28 UTC, eschrewe commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/dto/datatype/DT_ApiMethodEnum.java
>          this.PURPOSE = purpose;
Yes, when the older methods and classes will be removed, this can be removed as well

2024-01-17 15:30 UTC, eschrewe commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/controller/ItemStockRequestApiController.java
> +        log.info("Got Request\n" + requestMessageDto);
Validator was inserted now

2024-01-17 15:30 UTC, eschrewe commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/controller/ItemStockRequestApiController.java
> +            log.warn("Received invalid request\n" + requestMessageDto);
Validator was inserted now

2024-01-17 15:31 UTC, eschrewe commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/controller/ItemStockRequestApiController.java
> +                log.warn("Missing direction in request \n" + requestMessageDto);
Validator was inserted now

2024-01-17 15:31 UTC, eschrewe commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/controller/ItemStockResponseApiController.java
> +        log.info("Received response: \n" + responseDto);
Validator was inserted now

2024-01-17 15:32 UTC, eschrewe commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/controller/ItemStockResponseApiController.java
> +            log.error("Response dto does not match any open request: \n" + responseDto);
Validator was inserted now

2024-01-17 15:34 UTC, eschrewe commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/logic/service/ItemStockRequestApiService.java
> +                log.error("Wrong direction in request from customer \n" + requestMessageDto);
Validation of externally created dto's is done in the controller classes (see above).

2024-01-17 15:35 UTC, eschrewe commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/logic/service/ItemStockRequestApiService.java
> +                log.error("Unknown Partner in request \n" + requestMessageDto);
Validation of externally created dto's is done in the controller classes (see above).

2024-01-17 15:35 UTC, eschrewe commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/logic/service/ItemStockRequestApiService.java
> +                log.error("Unknown Partner in request \n" + requestMessageDto);
Validation of externally created dto's is done in the controller classes (see above).

2024-01-17 15:37 UTC, eschrewe commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/controller/EdcController.java
> +            if(!PatternStore.NON_EMPTY_NON_VERTICAL_WHITESPACE_STRING.matches(assetId)) {
CodeQL does not understand that this Pattern matching excludes all newline characters.

2024-01-18 14:15 UTC, tom-rm-meyer-ISST approved these changes
LGTM, PR has been smaller in the beginning but needed enhancements to prevent log injection that resulted in bigger refactorings. Around 200 lines should be just license headers, did not count further documentation.

2024-01-18 14:16 UTC, merged