Ci: docker compose for local test scenario
eclipse-tractusx/puris pull request #24
Opened 2023-08-29 08:24 UTC by tom-rm-meyer-ISST

## Description
Introduced a docker-compose for local test demonstration. Spins up following containers needed for edc 0.3.0
- one PURIS backend for customer and supplier each
- one PURIS frontend for customer and supplier each
- one control plane for customer and supplier each
- one data plane for customer and supplier each
- one postgresql
- one vault

It provides additional setup scripts and configuration for the given scenario.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-08-29 13:33 UTC, tom-rm-meyer-ISST commented
Quality check still fails because we need to incorporate this issue: https://github.com/eclipse-tractusx/sig-infra/issues/230

2023-08-29 13:42 UTC, tom-rm-meyer-ISST commented
Updated license headers.

2023-10-20 11:04 UTC, mhellmeier commented
Regarding postgresql, remember to have a look at https://github.com/eclipse-tractusx/sig-infra/discussions/308

2023-11-03 14:25 UTC, tom-rm-meyer-ISST commented
Regarding quality checks: The TRG for base images only applies to publishing images. As we use it locally for integration test, it's fine. I added the exclusion already to the metadata file. As soon as the reusable workflow is ready, it will pass. See [here](https://github.com/eclipse-tractusx/tractusx-quality-checks/blob/main/docs/metadata_file.md).

2023-11-03 14:44 UTC, tom-rm-meyer-ISST commented
> Regarding quality checks: The TRG for base images only applies to publishing images. As we use it locally for integration test, it's fine. I added the exclusion already to the metadata file. As soon as the reusable workflow is ready, it will pass. See [here](https://github.com/eclipse-tractusx/tractusx-quality-checks/blob/main/docs/metadata_file.md).

Release guideline workflow has been updated. Everything works out now!

2023-11-03 16:46 UTC, mhellmeier requested changes
Different changes in the docker setup are necessary to get it working. I can fix it for you.

2023-11-03 16:46 UTC, mhellmeier commented on local/INSTALL.md
Different points aren't necessary here.

2023-11-03 16:46 UTC, mhellmeier commented on local/daps/docker-compose.yaml
> +version: '1'
Should be updated to version 3.

2023-11-03 16:46 UTC, mhellmeier commented on local/docker-compose.yaml
> +version: '2'
Should be updated to version 3.

2023-11-03 16:46 UTC, mhellmeier commented on local/tractus-x-edc/docker-compose.yaml
> +version: "1"
Should be updated to version 3.

2023-11-03 17:09 UTC, mhellmeier approved these changes
LGTM, since it is only a local deployment for testing purposes and the KICS issues are addressed in #79

2023-11-03 17:10 UTC, merged