Feat/dynamic supplier dashboard
eclipse-tractusx/puris pull request #25
Opened 2023-08-29 08:42 UTC by PaMarzec

## Description
* changed the dashboard to be dynamic 
* added mock data for "customer", "material" and "your stock"
* added the changing of backgroundcolor to red if production is lower than total demand

2023-08-29 13:47 UTC, tom-rm-meyer-ISST requested changes
Please update small fix and then let me know. For the next time: when doing a PR, please don't remove the second part of the PR. It reminds you of then performing the dashtool check and checking for missing license headers. If you did not check that, please also do :)

2023-08-29 13:47 UTC, tom-rm-meyer-ISST commented on frontend/src/views/SupplierDashboard.vue
> +                    <!--
please remove unused code

2023-08-30 09:40 UTC, tom-rm-meyer-ISST approved these changes
Thanks for fixing! @mhellmeier please merge.

2023-08-30 09:40 UTC, tom-rm-meyer-ISST approved these changes

2023-08-31 09:04 UTC, mhellmeier approved these changes
LGTM, since the failed Q-Gate pipeline is already addressed.

2023-08-31 09:10 UTC, merged