Update security-assessment.md
eclipse-tractusx/puris pull request #250
Opened 2024-02-16 09:31 UTC by szymonkowalczykzf

Added Mermaid Diagram.
Additionally removed Vulnerabilities number 5&7 (Rate Limitting & encryption of data at rest) due to the fact that they are still open and I believe we had an agreement to upload here only the addressed vulnerabilities.

I have already accepted the threat modeling requirement for the Quality Gate 24 March 2024.

Please review and approve.

## Description

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-02-16 11:59 UTC, tom-rm-meyer-ISST requested changes
Please add one comma for readability. Rest ist top! Wasn't aware of the native integration of mermaid in GIthub! :)

2024-02-16 11:59 UTC, tom-rm-meyer-ISST commented on docs/security-assessment.md
> +    B-->|List catalog negotiations \n and transfers, \n Read Access \n HTTPS Protocol|D2
please adjust to "List catalog, negotiations \n and transfers, ..." :)

2024-02-16 12:19 UTC, szymonkowalczykzf commented
@tom-rm-meyer-ISST Change implemented, did not catch up this one earlier, thanks.

2024-02-17 12:37 UTC, tom-rm-meyer-ISST approved these changes
LGTM, thanks for providing!

2024-02-17 12:37 UTC, merged