ci(owasp-dast): added workflow for DAST
eclipse-tractusx/puris pull request #252
Opened 2024-02-17 11:23 UTC by tom-rm-meyer-ISST

## Description

Create Owasp Zap Worklfow for DAST.

Tests two apis with api key, and overall frontend.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-02-17 11:25 UTC, tom-rm-meyer-ISST commented
Hey @RoKrish14, please review. I prepared two api tests on backend level, and the full test for the frontend. Please check. We'll need to wait for [this issue](https://github.com/eclipse-tractusx/sig-infra/issues/441#issuecomment-1948787026) to be handled to make use of the secrets.

Further Question: I remember you talking about open api. PR #251 now fixes the missing api key header config in swagger ui.

2024-02-17 18:47 UTC, RoKrish14 approved these changes

2024-02-17 18:47 UTC, RoKrish14 commented on .github/workflows/owasp-dast.yaml
LGTM 👍

2024-02-22 09:46 UTC, RoKrish14 approved these changes

2024-02-22 11:32 UTC, RoKrish14 requested changes
Since we dont have access to secrets,
- you can remove secrets from - `secrets.API_KEY`
- keep only - `API_KEY`

2024-02-23 10:53 UTC, tom-rm-meyer-ISST commented
> Since we dont have access to secrets,
> 
> * you can remove secrets from - `secrets.API_KEY`
> * keep only - `API_KEY`

incorporated

2024-02-23 12:00 UTC, RoKrish14 approved these changes

2024-02-23 14:11 UTC, mhellmeier approved these changes

2024-02-23 14:11 UTC, merged