Refactor/dtr registrationtasks
eclipse-tractusx/puris pull request #356
Opened 2024-05-07 07:13 UTC by eschrewe

## Description
- Removed DtrRegistrationTask from MaterialServiceImpl
- Refactored DtrRegistrationTask in MaterialPartnerRelationImpl for better resilience
- previously, a product registration was not performed as long as an eventual material registration failed, under these circumstances, all registrations failed in cases where two partners are supplier und customer for the same material to each other
- edited the DataInjectionCommandlineRunner in order to test the aforementioned scenario. It is debatable whether these changes should be included into the main branch. If not, we should remove them before merging. 
- Updated DTR to version 0.4.3 (from 0.3.23)
- included API changes resulting from that upgrade
- removed unused fields from DigitalTwinMapping entity
- in ItemStockSammMapper, replaced warnings with IllegalArgumentExceptions, because otherwise a faulty Samm would cause the ItemStockRequestApiService would delete all previous ItemStock data without receiving update data from a valid Samm. 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-05-13 11:10 UTC, tom-rm-meyer-ISST requested changes
Great refactoring. I would keep the CommandLineRunner changes. Please add some more javadoc. Just small findings.

2024-05-13 12:24 UTC, eschrewe commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/service/MaterialPartnerRelationServiceImpl.java
> +        final boolean needProductRegistration;
Done. 

After some more consideration, i also added some more safety measures to the DTR registration task. Another possible point of failure lies within the initialisation of the "allCustomers" variable. It is at least a possibility, that the write operations to the MPR-database within the MPR-Services "create" and "update" methods have not finished, when the DtrRegistration Task arrives at that point (now: line 258). 

That means: in a bad case scenario the "allCustomers"-List does not contain the customer partner that is referenced to in the MPR. But regardless of that, the previous version of the code would not have noticed that and would potentially have declared a success (although the partner in question still is not referenced in the AAS). 

To added further safety, i also added a smaller waiting period even during the first try (see line 254), in order to give the database-write operation more time to finish, before the DTRRegistration Task moves on.

2024-05-13 12:25 UTC, eschrewe commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/service/MaterialPartnerRelationServiceImpl.java
> +                        var futureResult = executorService.submit(new PartTypeInformationRetrievalTask(materialPartnerRelation, 1));
Done!

2024-05-14 05:28 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/masterdata/logic/service/MaterialPartnerRelationServiceImpl.java
> +        final boolean needProductRegistration;
I guess in future we should synchronize threads for such issues and have a lock on the db to be transaction safe. But good finding!

2024-05-14 05:30 UTC, merged