feat: implemented the backend for demand and capacity notifications 2.0
eclipse-tractusx/puris pull request #415
Opened 2024-05-28 08:35 UTC by ReneSchroederLJ

## Description

- implemented the CRUD endpoints for demand and capacity notications

resolves #316 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-05-28 13:44 UTC, tom-rm-meyer-ISST requested changes
Overall great work. Had a few findings. 

Sidenote: Please always mark the dependency and license header things in the pr on your own prior to requesting the review :)

2024-05-28 13:44 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/notification/domain/model/Notification.java
> +public abstract class Notification {
Please rename the Classes to `DemandAndCapacityNotification` as that's the actual kind of notification. Please reconsider also for Service and Controller. (On controller level maybe the encapsulation makes sense?)

2024-05-28 13:44 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/notification/logic/service/OwnNotificationService.java
> +    public boolean validate(OwnNotification notification) {
Please follow recommendation for readability

2024-05-28 13:44 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/notification/logic/service/ReportedNotificationService.java
> +    public boolean validate(ReportedNotification notification) {
Please follow recommendation for readability

2024-05-28 13:44 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/notification/domain/model/Notification.java
> +    protected String text;
please add pattern check.

2024-05-28 13:44 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/notification/domain/model/Notification.java
> +
missing property: `sourceNotificationId` 
Is uuid = notificationId?

2024-05-28 13:44 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/notification/logic/dto/NotificationDto.java
> +    private String text;
pattern validation needed

2024-05-28 13:44 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/notification/logic/dto/NotificationDto.java
> +    private UUID relatedNotificationId;
`sourceNotificationId` missing

2024-05-29 11:02 UTC, ReneSchroederLJ commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/notification/domain/model/Notification.java
> +public abstract class Notification {
Yes. The interface for handling communication with the EDC is too extensive to include in the same PR and will be handled separately

2024-05-29 15:41 UTC, tom-rm-meyer-ISST reviewed
Please see new comment. Regarding bpnl sanitizing: not sure if you missed the comment, please check. If you propose to not go with sanitizing the controllers parameter, please elaborate why.

2024-05-29 15:41 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/notification/logic/dto/NotificationDto.java
> +public class NotificationDto implements Serializable {
@ReneSchroederLJ is not renaming this Dto similar to services, controllers, model on purpose? Else I propose to also rename and maybe also change the route of the controller to dcm-notification to use the same wording everywhere.

2024-05-30 06:59 UTC, ReneSchroederLJ commented
> Please see new comment. Regarding bpnl sanitizing: not sure if you missed the comment, please check. If you propose to not go with sanitizing the controllers parameter, please elaborate why.

I'm unsure what you mean regarding the BPNL sanitizing. Is the pattern check I added to the parameter not enough?

2024-05-30 07:41 UTC, tom-rm-meyer-ISST commented
> > Please see new comment. Regarding bpnl sanitizing: not sure if you missed the comment, please check. If you propose to not go with sanitizing the controllers parameter, please elaborate why.
> 
> I'm unsure what you mean regarding the BPNL sanitizing. Is the pattern check I added to the parameter not enough?

Ah sorry, you're right. Got confused due to the outdated conversation.

2024-05-30 07:41 UTC, tom-rm-meyer-ISST approved these changes
LGTM, great contribution! :)

2024-05-30 07:41 UTC, merged