fix(DeliveryRequestApiService): filter deliveries requested by partner role and incoterms
eclipse-tractusx/puris pull request #435
Opened 2024-06-03 16:18 UTC by tom-rm-meyer-ISST

## Description

resolves #432 

Maybe we need also to do similar enhancements to the following fields
- `DeliveryService` / `OwnDeliveryService`
- Frontend > incoterm and partner relationship including current role in dashboard (not sure, if we already have it but I think there is something in place)

Please let me know what you think. Based on the changes I would release a patch version

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-06-04 09:07 UTC, ReneSchroederLJ requested changes
Thank you for your contribution. 

Overall solid work, but besides a comment I left on a bug there seems to be an issue with how the material is retrieved in `handleDeliverySubmodelRequest`. There is a disconnect between the comment and what is actually happening. 

At first we attempt to find the material by assuming that we are supplier and the Cx number is our own. If this fails we should check if we are customer and the Cx number matches the partnerCxNumber in any mpr for that partner. only if that fails we should `triggerPartTypeRetrieval` and afterwards check the mpr again.

Currently we do not check the mpr at all so we can not handle requests where we are the customer.

2024-06-04 16:45 UTC, tom-rm-meyer-ISST commented
> Thank you for your contribution.
> 
> Overall solid work, but besides a comment I left on a bug there seems to be an issue with how the material is retrieved in `handleDeliverySubmodelRequest`. There is a disconnect between the comment and what is actually happening.
> 
> At first we attempt to find the material by assuming that we are supplier and the Cx number is our own. If this fails we should check if we are customer and the Cx number matches the partnerCxNumber in any mpr for that partner. only if that fails we should `triggerPartTypeRetrieval` and afterwards check the mpr again.
> 
> Currently we do not check the mpr at all so we can not handle requests where we are the customer.

Well seen! While implementing the change and a test to do it I recognized that this might even be unwanted behavior: If we don't have the CX ID when being customer, this means we did not create a Shell Descriptor with a href. Someone tries to access data directly via the asset / interface without the DTR to see how to access the data. 

I added a warning message as I think this could be a security issue, if a partner tries to do that.

2024-06-04 16:49 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/delivery/logic/service/DeliveryRequestApiService.java
> +            if (partnerIsCustomer) {
Great catch! updated + tests updated

2024-06-05 07:18 UTC, ReneSchroederLJ approved these changes
Looks good to me. Thank you for your efforts.

2024-06-05 09:36 UTC, tom-rm-meyer-ISST commented
Bumped version to create a patch release

2024-06-05 11:27 UTC, mhellmeier approved these changes

2024-06-05 11:30 UTC, merged