feat: implemented edc data exchange for DemandAndCapacityNotification
eclipse-tractusx/puris pull request #447
Opened 2024-06-13 11:13 UTC by ReneSchroederLJ

## Description
- implemented SAMM model for DemandAndCapacityNotification 2.0
- created the logic for sending Notifications as POST requests through the EDC

resolves #193 and #196 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-06-13 16:08 UTC, tom-rm-meyer-ISST requested changes
Thanks for contributing! As always great quality. We have some misunderstanding regarding notifications: these are not added as submodels at the registry for a material. 

Let's have a Chat on that :)

2024-06-13 16:08 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/demandandcapacitynotification/logic/adapter/DemandAndCapacityNotificationSammMapper.java
> +                .materialGlobalAssetId(affectedMaterialGlobalAssetIds)
We should add tests to mapping of these edge cases

2024-06-17 16:24 UTC, tom-rm-meyer-ISST requested changes
Great refactoring! Only had a few smaller findings. Please merge main; then I'll gonna check it in action :)

2024-06-17 16:24 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/demandandcapacitynotification/logic/service/DemandAndCapacityNotifcationRequestApiService.java
> +    public static final String DEMAND_AND_CAPACITY_NOTIFICATION_VERSION = "3.0.0";
please rename constant to `MESSAGE_HEADER_VERSION`

2024-06-17 16:24 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/demandandcapacitynotification/logic/dto/demandandcapacitynotficationsamm/DemandAndCapacityNotificationSamm.java
> +
please remove blank lines in import

2024-06-17 16:24 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/demandandcapacitynotification/logic/service/DemandAndCapacityNotifcationRequestApiService.java
> +
please remove blank lines in import

2024-06-17 16:24 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/demandandcapacitynotification/logic/adapter/DemandAndCapacityNotificationSammMapper.java
> +                .materialGlobalAssetId(affectedMaterialGlobalAssetIds)
raised issue #465

2024-06-18 07:14 UTC, ReneSchroederLJ commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/common/util/VariablesService.java
> +    @Value("${puris.baseurl}" + "catena/demand-and-capacity-notification/request")
catena is part of all asset endpoint variables. If this is an issue we need to address it for all of them I think

2024-06-18 12:26 UTC, tom-rm-meyer-ISST requested changes
Great work, works as a charm. I just realized that we have the semanticId set in the notificationId Asset Defintion which is not needed.

2024-06-18 12:26 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/logic/util/EdcRequestBodyBuilder.java
> +        var semanticIdObject = MAPPER.createObjectNode();
please remove semanticId object as it's not needed per standard. Also `privateProperties` are not needed.

2024-06-18 12:29 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/common/util/VariablesService.java
> +    @Value("${puris.baseurl}" + "catena/demand-and-capacity-notification/request")
True, currently also refactored for existing endpoints here: https://github.com/eclipse-tractusx/puris/pull/443/files#diff-24c2a742f6a2ddaa2cba86e31aa9c04edabba5b10b85d6017e4225f959faa4c1

2024-06-21 15:05 UTC, tom-rm-meyer-ISST requested changes
Thanks a lot, please decrease chart version again, as no 2.6.4 has been released yet

2024-06-21 15:05 UTC, tom-rm-meyer-ISST commented on charts/puris/Chart.yaml
> +version: 2.6.5
Please change again to 2.6.4. I finally managed to make the job for helm fail but not block merging for not bumping versions. Also updated future PR templates. See #450

2024-06-21 15:20 UTC, tom-rm-meyer-ISST approved these changes
LGTM, thanks a lot!

Helm version stays as stated in earlier comments

2024-06-21 15:21 UTC, merged