refactor: add deployment script for local deployment
eclipse-tractusx/puris pull request #469
Opened 2024-06-20 07:24 UTC by tom-rm-meyer-ISST

## Description

The following changes have been made:
- backend + chart: replace health controller by spring actuator plugin 
- local deployment
  - update generate keys:
    - fixed wrong parameters for keycloak miw_client (not sure why it worked without the script but not with the script)
    - Add a secret version file for docker to be used in newman
  - add `docker-compose-newman.yaml` to seed the int test data, if wanted (still need to remove role manually)
  - add `deploy.sh` which provides one-line deployments for common scenarios (full clean, only clean and create puris and direct direct dependencies, also seed int test data)
- postman: add 25 seconds waiting period after mad tests so that the backend may create the submodel descriptors and tests can be run fully automated.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-06-20 07:56 UTC, tom-rm-meyer-ISST commented
@eschrewe please already review this PR. 

I'll meanwhile will work on the worfklow in pr #450 to not enforce the update of the version as we sometimes want to bundle the chart changes for one release and not release every change directly.

2025-02-21 14:15 UTC, tom-rm-meyer-ISST commented
Two things to consider: 

- 1kloc limit is not applicable to committers.
- Helm chart fails due to version not increased (will be done during release)

2025-03-03 09:47 UTC, ReneSchroederLJ requested changes
Great contribution. The deployment script works really well. Mainly some suggestions for usability and documentation.

However, there is one bigger topic. I realized that all scripts in the repo are defined with the shebang for bash ( `#!/bin/bash` ), but being run with the regular `sh` shell. The regular shell doesn't support all features of bash. Currently this is not leading to compatibility issues, but we shouldn't rely on it. 

This could either be remedied by changing the files to use `#!/bin/sh` or running them with bash instead.

2025-03-12 17:47 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/common/security/SecurityConfig.java
> + * Copyright (c) 2022 Contributors to the Eclipse Foundation
wasn't on purpose. updated

2025-03-12 17:47 UTC, tom-rm-meyer-ISST commented on local/INSTALL.md
> +sh deploy.sh -ci
updated.

2025-03-12 17:47 UTC, tom-rm-meyer-ISST commented on local/deploy.sh
> +      echo "-p puris         = start PURIS, same result as 'docker compose up' with previous 'docker compose down -v'"
updated

2025-03-13 09:59 UTC, ReneSchroederLJ commented on local/INSTALL.md
> +sh deploy.sh -l
> Issue with that way is that the attach is done after all logs have run through. You don't know what happened before. I added a short  docker compose log on the backends before the attach. If you don't want the logs, I need to remove the line (feel free to do it as suggestion).

Maybe I'm missing something, but my idea would be to check whether or not to run in attached mode before running `docker compose up` the first time and then running either `docker compose up -d` or the attached variant directly. This way the logs for the backends are caught from the beginning.

The idea behind having an attached option is that it enables a straightforward way of running the local deployment with a single command that automatically shows the most relevant logs for local development. Using the `-l` flag also includes all EDC and DTR logs, which, in my personal experience, are often unnecessary. It's a compromise between offering the behavior of docker compose and convenience.

2025-03-13 10:21 UTC, ReneSchroederLJ commented on local/INSTALL.md
> +sh deploy.sh -l
> Maybe I'm missing something
I realized that this isn't possible, because it would block the terminal for the following commands. My apologies. The reasoning for having an attached option remains true regardless.

2025-03-13 15:50 UTC, ReneSchroederLJ approved these changes
LGTM thank you for your work

2025-03-13 16:06 UTC, tom-rm-meyer-ISST commented
@mhellmeier The chart is failing on purpose. I know it's > 1kloc but only I've been working on it.

2025-03-14 08:46 UTC, mhellmeier commented on local/cleanup.sh
> +# Copyright (c) 2024 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer ISST)
```suggestion
# Copyright (c) 2025 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer ISST)
```

2025-03-14 08:47 UTC, mhellmeier commented on local/docker-compose-infrastructure.yaml
> +# Copyright (c) 2023,2024 Contributors to the Eclipse Foundation
Also adjust the years here.

2025-03-14 09:31 UTC, tom-rm-meyer-ISST commented on local/docker-compose-infrastructure.yaml
> +# Copyright (c) 2024 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer ISST)
```suggestion
# Copyright (c) 2025 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer ISST)
```

2025-03-14 09:32 UTC, tom-rm-meyer-ISST commented on local/docker-compose-infrastructure.yaml
> +# Copyright (c) 2023,2024 Contributors to the Eclipse Foundation
done

2025-03-14 09:35 UTC, mhellmeier approved these changes
Thanks for updating. The failed pipeline aspect was already discussed. The >1k LOC are okay for me since you are a Committer, and they are mostly related due to auto-generated files like JSON package lock files.

2025-03-14 10:02 UTC, merged