feat: add bruno int test collection
eclipse-tractusx/puris pull request #546
Opened 2024-08-16 07:08 UTC by eschrewe

## Description
- added bruno test collection

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files
- [x] If helm chart has been changed, the chart version has been bumped to either next major, minor or patch level (compared to released chart).

2024-08-19 07:40 UTC, tom-rm-meyer-ISST requested changes
Thanks a lot! Works great. I checked both, the GUI & the CLI usage and it works fine!

Had a few minor findings.

I already checked the license for the CLI and filed one IP check: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15955

Please handle comments. I'll then file a request at the EF.

2024-08-19 07:40 UTC, tom-rm-meyer-ISST commented on local/bruno/puris-integration-test/collection.bru
Please copy the `README.md` from `postman` to `bruno`.

In the postman folder's file add a disclaimer in the beginning, like "The postman collection won't be continued after R24.08. Please refer to the Bruno collection" with a link to the bruno folder.

We could also think about removing it already - which would be even cleaner and we already have the IP check.

2024-08-19 08:53 UTC, eschrewe commented on local/bruno/puris-integration-test/environments/puris integration test env.bru
I don't think that is sensible. If I would do what you asked here, then removal of the B64-Varaibles (see above) could not be done (since I would be unable to push that to Github ;)

But I also don't think that thiis is necessary: By default, those six Variables, that contain secret keys are left blank by default. Everyone needs to insert the required data there manually from the .env file.

2024-08-19 09:34 UTC, tom-rm-meyer-ISST commented on local/bruno/puris-integration-test/environments/puris integration test env.bru
TL;DR I can't achieve what I wanted to achieve with the `.gitignore` - renaming would still be great :)

Rechecked that and actually `.gitignore` is not considered as I thought it would be considered:
- if you add a file for the first time, you need to use the force flag (`git add -f filename`)
- if you modify a file (our case), you can add it without focrce flag.

Thus I agree, that it's not suitable.

Regarding the latter: Yes, they are left default but ASAP I change them via bruno / intelliJ they are listed as changed and thus added automatically to intelliJs commit dialog, which allows commit by accident - I didn't find a way to remove that setting (Version Control > Confirmation only applies to creating and deleting files).

In command line interface git, it's working fine. Thus I'll need to cope with that and keep it in mind:D

2024-08-20 06:07 UTC, tom-rm-meyer-ISST reviewed
LGTM! Thanks a lot.

Regarding Trufflehog i raised [PR#555](https://github.com/eclipse-tractusx/puris/pull/555).

As we got plenty lines of code I raised an [EF IP issue](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15962). I will approve and merge as soon as we got the response :)

2024-08-21 05:30 UTC, merged