chore: edited license headers
eclipse-tractusx/puris pull request #562
Opened 2024-08-22 08:51 UTC by eschrewe

## Description
- changed license header copyright year, where necessary
- solves #528

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files
- [x] If helm chart has been changed, the chart version has been bumped to either next major, minor or patch level (compared to released chart).

2024-08-22 09:02 UTC, eschrewe commented
Won't do chart version bumb here...

2024-08-26 13:09 UTC, tom-rm-meyer-ISST requested changes
Thanks a lot! Found 4 places where 2023 has been placed instead of 2024.

Added suggestion so that you can also add them to a commit as a batch, via files tab :)

Please check :)

2024-08-26 13:09 UTC, tom-rm-meyer-ISST commented on local/generate-keys.sh
> +# Copyright (c) 2023 Contributors to the Eclipse Foundation
Seems like a copy and paste issue :)
```suggestion
# Copyright (c) 2022 Volkswagen AG
# Copyright (c) 2022 Contributors to the Eclipse Foundation
```

2024-08-26 13:09 UTC, tom-rm-meyer-ISST commented on local/init-wallets.sh
> +# Copyright (c) 2023 Contributors to the Eclipse Foundation
Seems like a copy and paste issue :)
```suggestion
# Copyright (c) 2022 Volkswagen AG
# Copyright (c) 2022 Contributors to the Eclipse Foundation
```

2024-08-26 13:09 UTC, tom-rm-meyer-ISST commented on local/vault/put-keys.sh
> +# Copyright (c) 2023 Contributors to the Eclipse Foundation
Seems like a copy and paste issue :)
```suggestion
# Copyright (c) 2022 Volkswagen AG
# Copyright (c) 2022 Contributors to the Eclipse Foundation
```

2024-08-26 13:09 UTC, tom-rm-meyer-ISST commented on local/cleanup.sh
> +# Copyright (c) 2023 Contributors to the Eclipse Foundation
Seems like a copy and paste issue :)
```suggestion
# Copyright (c) 2022 Volkswagen AG
# Copyright (c) 2022 Contributors to the Eclipse Foundation
```

2024-09-02 05:05 UTC, tom-rm-meyer-ISST approved these changes
LGTM, thanks for raising!

2024-09-02 05:05 UTC, merged