feat: implemented days of supply edc integration
eclipse-tractusx/puris pull request #694
Opened 2024-11-27 16:41 UTC by ReneSchroederLJ

## Description

- add SAMM models for Days of Supply
- implemented logic for registering the corresponding Assets and Contract
- implemented the request service for exchanging Days of Supply through the EDC

reolves #312 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files
- [x] If helm chart has been changed, the chart version has been bumped to either next major, minor or patch level (compared to released chart).

2024-11-27 17:14 UTC, ReneSchroederLJ commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/logic/service/DaysOfSupplyRequestApiService.java
> +            log.error("Could not identify Material-Partner Relation with material number " + materialNumberCx + " and partner bpnl " + partner.getBpnl());
The value for `materialNumberCx` is verified as URN or UUID before use and should not pose a risk.

2024-12-20 12:20 UTC, tom-rm-meyer-ISST requested changes
Got some smaller changes. Likely we should instead of solving a few things open issues to do a refactoring.

The updates broke the following test cases of the bruno collection
- Test_02-EDC/Check from Customer POV/Query catalog for Submodel Assets
- Test_02-EDC/Check from Supplier POV/Query catalog for Submodel Assets 
The test, Test_01-MAD/01_01-Init/Customer/MAD/Get All Partners has been missed by me during a recent fix.
- Also the ShellDescriptors should be checked regarding the new submodels

I'm wondering if this should also be handled with a separate pr and if we should do the PR also against a feature branch. Then we could handle the quick things in this pr. Additional stuff (update bruno collection, some javadoc) on the branch, too and we just merge the feature fully. Feel free to also reach out to me via MS teams to quickly align here.

2024-12-20 14:16 UTC, tom-rm-meyer-ISST requested changes
Thanks for incorporating. Just a small version change missing. You can directly commit via suggestion! Re-request review for merge

2024-12-20 14:16 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/common/edc/domain/model/AssetType.java
> +    DAYS_OF_SUPPLY("urn:samm:io.catenax.days_of_supply:2.0.0#DaysOfSupply", "$value", "DaysOfSupply", "1.0"),
```suggestion
    DAYS_OF_SUPPLY("urn:samm:io.catenax.days_of_supply:2.0.0#DaysOfSupply", "$value", "DaysOfSupply", "2.0"),
```

2024-12-20 14:16 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/logic/service/CustomerSupplyService.java
> -            (daysOfSupply.getStockLocationBPNA().equals(null) || daysOfSupply.getStockLocationBPNA().equals(daysOfSupply.getStockLocationBPNS()));
you;re right. Good catch (Y)

2024-12-20 14:16 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/logic/adapter/DaysOfSupplySammMapper.java
> +        for (var supplyBySite : suppliesBySite) {
should have removed that.

2024-12-20 14:16 UTC, tom-rm-meyer-ISST commented on backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/logic/adapter/DaysOfSupplySammMapper.java
> +        var material = materialService.findByMaterialNumberCx(matNbrCatenaX);
should have removed that.

2024-12-20 14:55 UTC, tom-rm-meyer-ISST approved these changes
LGTM, issues for remaining comments will be creaed by @ReneSchroederLJ (feel free to link the pr and close the issues).

Helm-Chart Link is ignored on purpose. Version Bump will be done during release.

2024-12-20 14:55 UTC, merged