fix: helm deployment with the follwing changes:
eclipse-tractusx/puris pull request #81
Opened 2023-11-09 09:14 UTC by PaMarzec

- feat: added new application.properties to deployment.yaml,values.yaml and their README's
- feat: splitted NOTES text to 'local' and 'internet' after deployment  with ingress enabled
- feat: added edc.controlplane.data.path to values.yaml's and to deployment.yaml

## Description
This PR adds the new application.properties to the associated values.yaml and deployment.yaml of the helm charts. Additionally it splits the deployment message into "local deployment" and "internet deployment"

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2023-11-10 12:52 UTC, mhellmeier submitted a review, later dismissed
Please check the checkboxes in the "Pre-review checks" section of your pull request section if you have done it.

2023-11-13 11:43 UTC, tom-rm-meyer-ISST requested changes
Good progress.
- Please update the pullPolicies for ALL images in helm
- Make the Frontend talk to the Backend out of the box using default values.
- Get the ingress running locally
- Harmonize backend application properties.

2023-11-13 11:43 UTC, tom-rm-meyer-ISST commented on charts/puris/charts/backend/templates/deployment.yaml
> +              value: "{{ .Values.puris.own.default.bpna }}"
Some of the own.default fields do have it but others don't. Could you please 
a) create an issue for harmonization
b) directly remove the default (all application properties with refactoring in intelliJ to also update the classes (VariablesServices, etc.), docker compose files and helm related files).

2023-11-13 11:43 UTC, tom-rm-meyer-ISST commented on charts/puris/values.yaml
Please change the pullPolicy always to "Always" -> supports debugging as we're currently only using main tag which updates the image that is then not pulled.
For me it didn't work otherwise.

2023-11-13 11:43 UTC, tom-rm-meyer-ISST commented on charts/puris/values.yaml
For my kubernetes puris.baseUrl is not working. The node port returns a 172. address and default variable points to 168. -> There is no connection between backend and frontend. 

Could we introduce a service alias or similar?

2023-11-13 11:43 UTC, tom-rm-meyer-ISST commented on frontend/INSTALL.md
> +helm install frontend --namespace puris --create-namespace . --set ingress.enabled=true --values ../../values.yaml
We need further instructions so that one can work with the enabled ingress. Otherwise its useless.

2023-11-13 11:43 UTC, tom-rm-meyer-ISST commented on charts/puris/charts/backend/templates/NOTES.txt
love that overall, but the locally reachable does not work if ingress is enabled. So we either need to come around this problem or need to remove it here again :(

2023-11-13 11:43 UTC, tom-rm-meyer-ISST commented on charts/puris/charts/backend/templates/deployment.yaml
> +              value: "{{ .Values.puris.own.default.bpna }}"
Maybe it makes sense to also update some of the default values in helm -> e.g. the edc address to something like http://YOUR-EDC-MANAGEMENT-URL/

2023-11-15 14:29 UTC, PaMarzec commented on charts/puris/values.yaml
I hard coded in the frontend values.yaml then baseUrl to 171... again to fix the Issue at first.
I also created the Issue  #87 to get rid of that problem in the future.

2023-11-16 19:10 UTC, tom-rm-meyer-ISST commented on charts/puris/values.yaml
Well documented, makes sense

2023-11-23 07:15 UTC, tom-rm-meyer-ISST requested changes
Local Deployment via Install.md has some issues. I already scheduled a meeting to go through a few of the comments. Please check all beforehand :)

2023-11-23 07:15 UTC, tom-rm-meyer-ISST commented on INSTALL.md
> +    --set backend.puris.own.name={"YOUR-APPLICATION-NAME"} \
Remove this one and just set to puris please

2023-11-23 07:15 UTC, tom-rm-meyer-ISST commented on INSTALL.md
> +    --set backend.puris.own.site.name={YOUR-SITE-NAME} \
Why do some examples contain " and others don't?

2023-11-23 07:15 UTC, tom-rm-meyer-ISST commented on INSTALL.md
> +    --set frontend.ingress.enabled=true \
Did you try to replace the values and run it locally? For me this results in problems with the ingress:
- Ingress needs lowercase (internal validation I wasn't aware of).
- when setting values in an array, the others are reset ([bug / feature discussion](https://github.com/helm/helm/issues/5711#issuecomment-636177594)) -> we should at most set ingress to enabled and list the respective values that might be configured in a values file above the install.md

2023-11-23 07:15 UTC, tom-rm-meyer-ISST commented on charts/puris/charts/backend/templates/deployment.yaml
> +            - name: EDC_CONTROLPLANE_DATA_PATH
Currently there is a medium finding regarding the container running with low uuid. This [tutorial ](https://docs.bridgecrew.io/docs/bc_k8s_37) explains how to solve it. It has already been present but is a low hanging fruit :)

You can find your user id in the respective Dockerfile (8877) :)

2023-11-23 07:15 UTC, tom-rm-meyer-ISST commented on charts/puris/charts/frontend/values.yaml
> +  tls:
Let's discuss that via Instant Message :)

2023-11-23 07:15 UTC, tom-rm-meyer-ISST commented on charts/puris/charts/backend/templates/deployment.yaml
> +            - name: EDC_CONTROLPLANE_DATA_PATH
Same applies to frontend BUT NGINX ships with a 101 user. For this case I should discuss it in the office hour.

2023-12-06 18:27 UTC, tom-rm-meyer-ISST requested changes
Great work, fix typos please

2023-12-06 18:27 UTC, tom-rm-meyer-ISST commented on charts/puris/values.yaml
> +                url: "https://your-edc-adress:your-port/api/v1/dsp"
address

2023-12-10 08:42 UTC, tom-rm-meyer-ISST requested changes
I've faced one issue that led to a backend pod error loop as a constraint was violated in the initial setup. Please adjust default data for edc config.

2023-12-10 08:42 UTC, tom-rm-meyer-ISST commented on charts/puris/values.yaml
> +                url: "https://your-edc-address:your-port/api/v1/dsp"
I've had a constraint violation in my backend. Reason is that we evaluate that it's a valid uri. As ":your-port" does not match the format, the application will throw several errors. Thus, I propose a small further change. For the two addresses use management port 8181 and supplier port 8184.

2023-12-10 08:42 UTC, tom-rm-meyer-ISST commented on charts/puris/values.yaml
> +            -   host: "your-frontend-host-adress.com"
typo: address with double d please. Same for backend

2023-12-12 10:40 UTC, tom-rm-meyer-ISST approved these changes
LGTM, TRG fails due to charts folder that could not be refactored well in this branch. Will be fixed with #111.

Opened #118 to incorporate KICS findings.

2023-12-12 10:41 UTC, merged